import assert from 'node:assert/strict';
import {World,AssetRegistry} from '../../../../engine/index.js';
import {createWaystone} from './waystone.js';
import {createVitals} from './vitals.js';
import {VITALS_DEFAULTS as C} from './vitalsConfig.js';
import {collectSave,applySave,stringifyGameSave,parseGameSave} from '../save/saveState.js';
const assets=new AssetRegistry({palette:{}});
const spawn={x:1,y:2,z:3,yawDeg:90};
const points=[{id:'stoneA',pos:{x:20,y:30,z:4,yawDeg:180}},{id:'stoneB',pos:{x:-20,y:40,z:8,yawDeg:270}}];
function rig(restored=null,defs=points){
  const world=restored?.world || World.load({name:'waystone_fixture',terrain:null,structures:[],entities:[]},assets,{});
  const player=world.get('player')?.data || world.spawn('unit',spawn,{health:{hp:2,max:6,invuln:0},body:{vx:1,vy:2,vz:3,eyeH:1.6,grounded:true}},'player').data;
  const saves=[];let sim;
  sim=createWaystone(world,player,{waystones:defs,spawn,requestSave:()=>saves.push(collectSave(world))});
  return {world,player,sim,saves};
}
const r=rig();assert.deepEqual(r.sim.snapshot(),{waystoneId:null,pos:spawn});
assert.deepEqual(r.sim.onDeath(),spawn);assert.equal(r.player.components.health.hp,6);assert.equal(r.saves.length,0,'death is not an autosave');
assert.equal(r.sim.touch('unknown'),false);assert.equal(r.saves.length,0);
r.player.components.health.hp=1;
assert.equal(r.sim.touch('stoneA'),true);assert.equal(r.player.components.health.hp,6);
assert.deepEqual(r.sim.snapshot(),{waystoneId:'stoneA',pos:points[0].pos});assert.equal(r.saves.length,1);
assert.equal(r.saves[0].world.entities[0].components.health.hp,6,'save sees healed hearts');
assert.deepEqual(r.saves[0].world.state.waystone,{waystoneId:'stoneA',pos:points[0].pos},'save sees committed checkpoint');
assert.equal(r.world.state['save.x'],20);assert.equal(r.world.state['save.yaw'],180);
r.player.components.health.hp=1;r.sim.touch('stoneB');assert.equal(r.saves.length,2);
assert.deepEqual(r.sim.onDeath(),points[1].pos);assert.equal(r.player.components.health.hp,6);
const snapshot=r.sim.snapshot();snapshot.pos.x=999;snapshot.waystoneId='changed';
const returned=r.sim.onDeath();returned.y=999;assert.deepEqual(r.sim.snapshot(),{waystoneId:'stoneB',pos:points[1].pos},'public copies cannot alter checkpoint');
const bytes=stringifyGameSave(collectSave(r.world));
const loaded=rig(applySave(parseGameSave(bytes),assets));
assert.deepEqual(loaded.sim.snapshot(),r.sim.snapshot());assert.deepEqual(loaded.sim.onDeath(),points[1].pos);
assert.equal(stringifyGameSave(collectSave(loaded.world)),bytes,'collect/apply/collect is byte-stable');
const missing=rig(applySave(parseGameSave(bytes),assets),[]);
assert.deepEqual(missing.sim.onDeath(),points[1].pos,'saved point remains usable when the prop is not loaded');
const initial=rig();initial.player.transform.x=400;
const initialLoaded=rig(applySave(collectSave(initial.world),assets));
assert.deepEqual(initialLoaded.sim.onDeath(),spawn,'no-stone fallback survives moved-player save/load');
function sequence(){const t=rig();for(const id of ['stoneB','stoneA','stoneB']){t.player.components.health.hp=1;t.sim.touch(id);t.sim.onDeath();}return stringifyGameSave(collectSave(t.world));}
assert.equal(sequence(),sequence(),'same input sequence yields the same saved bytes');
const mutable=structuredClone(points), independent=rig(null,mutable);mutable[0].pos.x=999;independent.sim.touch('stoneA');
assert.equal(independent.sim.snapshot().pos.x,20,'authored point mutation cannot alter registered anchor');
assert.throws(()=>rig(null,[points[0],points[0]]),/duplicate/);
assert.throws(()=>rig(null,[{id:'bad',pos:{...spawn,x:NaN}}]),/invalid/);
const bad=rig();bad.world.state.waystone={waystoneId:'stoneA',pos:{...spawn,z:Infinity}};
assert.throws(()=>createWaystone(bad.world,bad.player,{waystones:points,spawn,requestSave(){}}),/saved checkpoint/);
const upgrade=rig();upgrade.player.components.health.max=9;upgrade.player.components.health.hp=1;
upgrade.sim.touch('stoneA');assert.equal(upgrade.player.components.health.hp,9,'heal reads the live upgraded maximum');
upgrade.player.components.health.hp=1;upgrade.sim.touch('stoneA');assert.equal(upgrade.saves.length,2,'each deliberate touch saves once, including repeats');
assert.equal(upgrade.player.components.health.hp,9);
const failedSave=rig();const callbackFail=createWaystone(failedSave.world,failedSave.player,{waystones:points,spawn,requestSave(){throw new Error('fixture storage unavailable');}});
assert.throws(()=>callbackFail.touch('stoneA'),/storage unavailable/);
assert.deepEqual(callbackFail.snapshot(),{waystoneId:'stoneA',pos:points[0].pos});
assert.equal(failedSave.player.components.health.hp,6,'save failure cannot roll back healing or corrupt checkpoint');
// Existing vitals uses the mirrored checkpoint: real death timeline + respawn, no second teleport implementation.
const live=rig(),events={on(){return ()=>{};}},vitals=createVitals(live.world,events,C);
vitals.step(live.player,false);live.sim.touch('stoneA');
live.player.components.health.hp=0;vitals.step(live.player,false);assert.equal(vitals.dead,true);
for(let i=0;i<C.sinkSteps+C.fadeSteps;i++)vitals.step(live.player,false);
vitals.step(live.player,true);
assert.equal(vitals.dead,false);assert.equal(live.player.transform.x,20);assert.equal(live.player.transform.y,30);
assert.equal(live.player.transform.z,4);assert.equal(live.player.transform.yawDeg,180);assert.equal(live.player.components.health.hp,6);
assert.equal(live.player.components.body.vx,0,'vitals owns body reset');
console.log('waystone: full healing, autosave ordering, last-point/fallback, canonical restore, deterministic sequence and existing vitals respawn PASS');
