import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { World, AssetRegistry } from '../../../../engine/index.js';
import { ensureInventory } from '../sim/inventory.js';
import { createQuest, applyQuestEvent } from '../sim/quest.js';
import { collectSave,applySave,stringifyGameSave,parseGameSave,createMemoryAdapter,createStorageAdapter } from './saveState.js';
const assets=new AssetRegistry({palette:{}}),world=World.load({name:'save_fixture',terrain:null,structures:[],entities:[]},assets,{});
const player=world.spawn('unit',{x:12.25,y:-3.5,z:2,yawDeg:123,pitchDeg:-9},{health:{hp:3,max:5,invuln:0},mana:{mp:7,max:10}},'player');
ensureInventory(player.data,{pack:[{id:'lantern',n:1},{id:'sword',n:1}],left:'lantern',right:'sword'});
const questDef=JSON.parse(readFileSync(new URL('../../../../content/quests/m1.quest.json',import.meta.url)));
const quest=createQuest(questDef);applyQuestEvent(quest,{type:'flag:set',key:'wake',value:true},questDef);
const options={quest,questDef,openedChests:['chestB','chestA','chestA'],deadBeasts:['boar2','boar1'],place:'Tower',playTimeSec:125.5};
const save=collectSave(world,options),text=stringifyGameSave(save);
const restored=applySave(parseGameSave(text),assets,{questDef});
assert.equal(restored.world.get('player').data.components.health.hp,3);
assert.equal(restored.world.get('player').data.components.mana.mp,7);
assert.equal(restored.world.get('player').data.components.inventory.left,'lantern');
assert.equal(restored.world.get('player').data.components.inventory.right,'sword');
assert.equal(restored.world.get('player').data.transform.x,12.25);
assert.equal(restored.world.get('player').data.transform.yawDeg,123);
assert.deepEqual(restored.openedChests,['chestA','chestB']);assert.deepEqual(restored.deadBeasts,['boar1','boar2']);
assert.deepEqual(restored.quest,quest);
assert.equal(stringifyGameSave(collectSave(restored.world,{...restored,...restored.meta,questDef})),text,'byte-stable collect/apply/collect');
world.get('player').data.components.health.hp=1;assert.equal(save.world.entities[0].components.health.hp,3,'snapshot has no aliases');
restored.quest.flags.wake=false;assert.equal(save.game.quest.flags.wake,true,'restore has no aliases');
const legacy=structuredClone(save);legacy.world.version=1;for(const e of legacy.world.entities)delete e.parent;
assert.equal(collectSave(applySave(legacy,assets,{questDef}).world).world.version,2,'public deserialize migrates WorldState v1');
const newer=structuredClone(save);newer.saveVersion=2;assert.throws(()=>applySave(newer,assets,{questDef}));
const bad=structuredClone(save);bad.meta.playTimeSec=NaN;assert.throws(()=>stringifyGameSave(bad));
const adapter=createMemoryAdapter();assert.equal(adapter.readSlot(0).save,null);
assert.equal(adapter.writeSlot(0,save).ok,true);assert.equal(adapter.writeSlot(2,save).ok,true);
assert.equal(stringifyGameSave(adapter.readSlot(0).save),text);
assert.equal(adapter.listSlots().length,3);assert.equal(adapter.listSlots()[1].meta,null);
assert.equal(adapter.listSlots()[0].meta.playerName,'Wick');assert.equal(adapter.deleteSlot(0).ok,true);
assert.equal(adapter.readSlot(0).save,null);assert.ok(adapter.readSlot(2).save,'slot deletion isolated');
assert.throws(()=>adapter.writeSlot(3,save));
const unavailable=createStorageAdapter({getItem:()=>{throw Error('privacy');},setItem:()=>{throw Error('quota');},removeItem:()=>{throw Error('privacy');}});
assert.equal(unavailable.writeSlot(0,save).ok,false);assert.equal(unavailable.readSlot(0).ok,false);assert.equal(unavailable.deleteSlot(0).ok,false);
const corrupt=createStorageAdapter({getItem:()=>'{bad',setItem:()=>{},removeItem:()=>{}});assert.equal(corrupt.readSlot(0).ok,false);
assert.equal(createStorageAdapter({getItem:()=>null,setItem:()=>{},removeItem:()=>{}}).writeSlot(0,save).ok,false,'read-back detects silent write loss');
assert.deepEqual(world.get('player').data.components.inventory,save.world.entities[0].components.inventory);
console.log('saveState: player components/hands, quest/chests/deaths, byte-stable round trip, CO-5 migration and isolated/error-safe slots PASS');
