import assert from 'node:assert/strict';
import {createUiLayer} from '../../../engine/index.js';
import {createMemoryAdapter} from '../quest/save/saveState.js';
import {createTitleMenu} from './titleMenu.js';
import '../../../design/models/title.js';
import '../../../design/models/menu_ui.js';
const save={saveVersion:1,world:{version:2,entities:[],structures:[]},game:{quest:null,openedChests:[],deadBeasts:[]},meta:{playerName:'Wick',place:'Tower',playTimeSec:3661}};
const adapter=createMemoryAdapter();adapter.writeSlot(0,save);adapter.writeSlot(2,save);
const menu=createTitleMenu(adapter,{style:ASSETS.uiStyle.menu}),ui=createUiLayer({cols:160}),b=menu.draw(ui);
const click=y=>menu.handlePointer(b.x+5,b.y+y);
assert.deepEqual(menu.snapshot().rows.map(r=>r.text),['New game','Continue','Load game','Settings','Credits']);
assert.equal(menu.handleKey('Delete'),false);assert.equal(menu.snapshot().mode,'main');
click(12);assert.equal(menu.snapshot().mode,'load');assert.deepEqual(menu.snapshot().rows.map(r=>r.enabled),[true,false,true,true]);
menu.handleKey('ArrowDown');assert.equal(menu.snapshot().selected,2,'empty slot skipped');
menu.handleKey('Enter');assert.deepEqual(menu.takeAction(),{type:'load',slot:2});assert.equal(menu.takeAction(),null);
click(12);assert.equal(click(11),false,'empty slot cannot load');menu.handleKey('Escape');assert.equal(menu.snapshot().mode,'main');
click(12);click(20);assert.equal(menu.snapshot().mode,'main');
click(9);assert.deepEqual(menu.takeAction(),{type:'continue',slot:0,save:adapter.readSlot(0).save});
click(15);assert.deepEqual(menu.takeAction(),{type:'settings'});
menu.handleKey('ArrowUp');menu.handleKey('Enter');assert.deepEqual(menu.takeAction(),{type:'credits'});
click(18);assert.deepEqual(menu.takeAction(),{type:'credits'});
menu.handleKey('Enter');assert.equal(menu.snapshot().mode,'new');menu.handleKey('Enter');assert.deepEqual(menu.takeAction(),{type:'newGame',slot:1});
menu.handleKey('Enter');click(8);assert.equal(menu.snapshot().mode,'confirm');assert.equal(menu.snapshot().selected,0);menu.handleKey('Enter');assert.equal(menu.takeAction(),null);assert.ok(adapter.readSlot(0).save);
menu.handleKey('Enter');click(8);menu.handleKey('ArrowDown');menu.handleKey('Enter');assert.deepEqual(menu.takeAction(),{type:'newGame',slot:0});assert.ok(adapter.readSlot(0).save,'view does not overwrite storage');
const empty=createTitleMenu(createMemoryAdapter());assert.equal(empty.snapshot().rows[1].enabled,false);empty.handleKey('ArrowDown');assert.equal(empty.snapshot().rows[empty.snapshot().selected].id,'load');empty.handleKey('Enter');assert.equal(empty.snapshot().selected,3);empty.handleKey('Enter');assert.equal(empty.snapshot().mode,'main');
const timestamped=createTitleMenu({listSlots:()=>[{slot:0,ok:true,meta:{...save.meta,savedAt:1}},{slot:2,ok:true,meta:{...save.meta,savedAt:2}}],readSlot:()=>({ok:true,save})});timestamped.handleKey('ArrowDown');timestamped.handleKey('Enter');assert.equal(timestamped.takeAction().slot,2);
const unreadable=createTitleMenu({listSlots:()=>[{slot:0,ok:false,meta:null}],readSlot:()=>({ok:false})});unreadable.draw(ui);unreadable.handlePointer(b.x+5,b.y+12);assert.equal(unreadable.snapshot().rows[0].enabled,false);
assert.throws(()=>createTitleMenu({}),/adapter required/);
const before=JSON.stringify(menu.snapshot());for(let i=0;i<100;i++)assert.equal(menu.draw(ui),b);assert.equal(JSON.stringify(menu.snapshot()),before);
assert.deepEqual([...ui.cells.bg.slice(((b.y+6)*ui.cols+b.x+10)*4,((b.y+6)*ui.cols+b.x+10)*4+4)],[52,42,16,255]);
console.log('Five-row menu, Load slots/grey empty/back, no delete, New overwrite safety, Continue/Settings/Credits actions and stable styled draw PASS');
