// WG-2b: draw order/ranges, integer uniforms, mirrored winding, sentinel/depth clear, resource reuse.
import assert from 'node:assert/strict';
import { makeMockGpuDevice } from '../../../test/assert.js';
import { StaticMeshBuilder } from '../../../mesh/MeshData.js';
import { DrawList, DRAW_STATIC, DRAW_VOXEL, DRAW_INSTANCED, DRAW_CLOTH } from '../../../mesh/DrawList.js';
import { WgRasterPass } from './passRaster.js';
import { RASTER_BLOCK } from '../wgsl/raster.wgsl.js';

const mock = makeMockGpuDevice(), d = mock.device;
const pass = new WgRasterPass(d), draws = [], clears = [];
d.beginPass = (target, opts) => clears.push({ target, opts });
d.draw = (count, first, instances) => draws.push({ pipe: d._activePipeline, count, first, instances,
  uniforms: new Uint32Array(d._lastBind.uniforms.buffer).slice(), bind: d._lastBind, extra: d._lastBind.extraBuffers && d._lastBind.extraBuffers[0] });
const builder = new StaticMeshBuilder('wg-raster-quad');
builder.addQuad([0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0], [0, 0, 1, 0, 1, 1, 0, 1], 0, 0, 1, 0xf0000001, 9 | (5 << 8) | (3 << 16), [0, 0, 0, 0, 0, 0, 0, 0]);
const mesh = builder.build(); mesh.ranges = [{ start: 0, count: 2 }];
const p = { _t: { targetRaster: {}, targetVmDepth: {} }, stats: {} };
const staticItem = pass.list.push(); staticItem.type = DRAW_STATIC; staticItem.mesh = mesh; staticItem.rangeCount = 2;
staticItem.planeIdOr = 0x90000000; staticItem.objectId = 0x8001; staticItem.zBase = 3;
staticItem.matrix.set([1, 0, 0, 0, 1, 0, 0, 0, 1, 4, 5, 6]);
const voxel = pass.list.push(); voxel.type = DRAW_VOXEL; voxel.mesh = mesh; voxel.mirror = 1;
voxel.partMatrices.set(staticItem.matrix); voxel.partFlags[0] = 1;
const instance = pass.list.push(); instance.type = DRAW_INSTANCED; instance.mesh = mesh;
instance.instBuf = { f32: new Float32Array(32) }; instance.instCount = 2;
instance.partMatrices.set(staticItem.matrix); instance.partFlags[0] = 1;
const vmList = new DrawList(1), vm = vmList.push();
vm.type = DRAW_VOXEL; vm.mesh = mesh; vm.partMatrices.set(staticItem.matrix); vm.partFlags[0] = 1;
pass.vmList = vmList;
pass.prepare = () => {};
pass.run(p);
assert.deepEqual(draws.map(x => [x.count, x.first, x.instances]), [[6, 0, 1], [6, 0, 1], [6, 0, 2], [6, 0, 1]]);
assert.deepEqual(draws.map(x => x.pipe.desc.frontFace), ['cw', 'ccw', 'cw', 'cw']);
assert.equal(draws[1].pipe.desc.cull, 'back');
assert.equal(draws[0].uniforms[RASTER_BLOCK.field('planeIdOr').word], 0x90000000);
assert.equal(draws[0].uniforms[RASTER_BLOCK.field('objectId').word], 0x8001);
assert.deepEqual([...new Float32Array(draws[0].uniforms.buffer)].slice(12, 16), [4, 5, 6, 1]);
assert.equal(draws[1].uniforms[RASTER_BLOCK.field('axisAligned').word], 1);
assert.equal(clears[0].opts.clear.color[2][0], 0x7f800000, 'empty depth cells retain infinity sentinel');
assert.equal(clears[1].target, p._t.targetVmDepth, 'viewmodel clear touches only shared depth');
assert.equal(clears[2].opts, undefined, 'viewmodel draw reloads world G-buffer');
assert.equal(p.stats.vmDraws, 1); assert.equal(p.stats.instances, 2);
const resources = mock.createCount, uniforms = pass.u, bindDesc = pass.bindDesc;
for (let i = 0; i < 1000; i++) pass.run(p);
assert.equal(mock.createCount, resources, 'warm frames allocate no buffers, textures, or pipelines');
assert.equal(pass.u, uniforms); assert.equal(pass.bindDesc, bindDesc);
assert.equal(mock.writeCount, 1000, 'instanced buffer is updated without recreation');
// Cloth: dynamic pos/normal buffer + static uv as an extra vertex stream; two-sided; flat words from the mesh material.
const uvBuf = d.createBuffer({ usage: 'vertex', bytes: 32 }), clothVb = d.createBuffer({ usage: 'vertex', bytes: 64 }), clothIb = d.createBuffer({ usage: 'index', bytes: 12 });
pass.buffers.getCloth = () => ({ vertexBuffer: clothVb, uvBuffer: uvBuf, indexBuffer: clothIb });
const cloth = pass.list.push(); cloth.type = DRAW_CLOTH; cloth.mesh = { matId: 7 }; cloth.rangeCount = 3; cloth.rangeFirst = 1; cloth.matrix.set(staticItem.matrix);
draws.length = 0; pass.run(p);
const cd = draws.find((x) => x.pipe === pass.clothPipe);
assert.equal(cd.pipe, pass.clothPipe); assert.equal(cd.pipe.desc.cull, 'none'); assert.equal(cd.pipe.desc.frontFace, 'cw');
assert.equal(cd.pipe.desc.vertex.extraLayouts[0].layout[0].location, 1, 'uv extra stream at location 1');
assert.equal(cd.extra, uvBuf); assert.equal(cd.count, 9); assert.equal(cd.first, 3);
assert.equal(cd.uniforms[RASTER_BLOCK.field('flat').word + 1] >>> 16, 7, 'cloth material in flat.y');
assert.equal(p.stats.clothDraws, 1);
pass.dispose(); d.dispose(uvBuf); d.dispose(clothVb); d.dispose(clothIb); assert.equal(mock.liveCount(), 0);
console.log('passRaster.test.js: all checks passed.');
