// SWAY-GC-01: static contract - the only gpucompare pose with wind on is `swayWindy` (fixed wind def + fixed timeSec); its shadow-depth row
// is generated by the shared per-pose loop. No other pose may set a wind override / depend on the wall clock.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const src = fs.readFileSync(path.join(path.dirname(fileURLToPath(import.meta.url)), 'gpucompare.js'), 'utf8');

assert.strictEqual((src.match(/wind: SWAY_GC_WIND/g) || []).length, 1, 'exactly one world gets the wind override');
assert.strictEqual((src.match(/SWAY_GC_WIND\b/g) || []).length, 2, 'SWAY_GC_WIND: one definition + one use');
const def = /const SWAY_GC_WIND = \{[^}]*speed: ([\d.]+)[^}]*seed: (\d+)/.exec(src);
assert.ok(def && +def[1] > 0 && Number.isInteger(+def[2]), 'wind def has speed > 0 and an explicit integer seed');
const pose = src.match(/name: 'world_m1: swayWindy[^']*'[\s\S]*?before: \(\) => engine\.setWorld\(swayWindWorld\) \}\);/);
assert.ok(pose, 'swayWindy pose present');
assert.ok(/timeSec: 7\.3/.test(pose[0]) && /meshOnly: true/.test(pose[0]), 'fixed timeSec, mesh only');
assert.strictEqual((src.match(/name: '[^']*swayWindy/g) || []).length, 1, 'one swayWindy pose (the shadow row is `<name> [shadow depth parity]`)');
assert.ok(/pose: `\$\{poseName\} \[shadow depth parity\]`/.test(src), 'shadow parity row is generated per pose');
assert.ok(!/Date\.now|performance\.now/.test(pose[0]), 'no wall clock in the pose');
console.log('PASS gpucompare.swayWind.test.js');
